name: Auto Assign PRs to Project
on:
  issues:
    types: [ opened ]
  pull_request:
    types: [ opened ]
    
# github-script: https://github.com/actions/github-script
# -> points to github rest (octokit) reference doc

# github PAT: https://github.com/settings/tokens
# must have full repo access

# FIXME how can I prevent a user from creating a PR and stealing my token?
# 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    
# curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ghp_..." https://api.github.com/projects/1/columns?owner=zpqrtbnk&repo=test-repo
# curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ghp_..." https://api.github.com/projects/1/columns?owner=zpqrtbnk-alt&repo=test-repo-alt
    
jobs:
  assign:
    runs-on: ubuntu-latest
    name: Assign
    steps:
    - name: Assign
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN_TESTREPO }}
        script: |
            //const project_name = 'The API Team Board'
            //const column_name = 'Drafting'
            
            const project_name = 'test-project'
            const column_name = 'To do'
            
            function firstOrDefault(items, predicate) {
                for (const item of items) {
                    if (predicate(item)) {
                        return item
                    }
                }
                return null
            }
            
            // find the project
            console.log('find project...')
            const projects = await github.projects.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo
            })
            console.log(`retrieved ${projects.data.length} projects.`)
            const project = firstOrDefault(projects.data, (x) => x.name === project_name)
            if (project === null) {
                core.setFailed(`Failed to find project "${project_name}".`)
                return
            }
            else {
                console.log(`project id: ${project.id}.`)
            }

            // find the column
            console.log('find column...')
            const columns = await github.projects.listColumns({
                project_id: project.id
            })
            console.log(`retrieved ${columns.data.length} columns.`)
            const column = firstOrDefault(columns.data, (x) => x.name === column_name)
            if (column === null) {
                core.setFailed(`Failed to find column "${column_name}" in project ${project.name}.`)
                return
            }
            else {
                console.log(`column id: ${column.id}.`)
            }
            
            // determine content type
            console.log('determine content type...')
            const event_name = context.eventName
            var content_type = null
            if (event_name === 'issues') {
                content_type = 'Issue'
            }
            if (event_name === 'pull_request') {
                content_type = 'PullRequest'
            }
            if (content_type === null) {
                core.setFailed(`Unexpected event name "${event_name}".`)
                return
            }
            else {
                console.log(`content type: ${content_type}.`)
            }
            
            // get the issue/pr
            console.log('get the issue/pr...)
            const item = await github.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number
            })
            if (item === null) {
                core.setFailed(`Failed to get issue ${context.issue.number}.`)
                return
            }
            else {
                console.log(`issue id: ${item.id}.`)
            }
                        
            console.log('create the card...')
            console.log(`in column ${column.id} for item ${item.id} of type ${content_type}`)
            await github.projects.createCard({
                column_id: column.id,
                //note:,
                content_id: item.id,
                content_type: content_type
            })
            console.log('created')
            
            /*
            await github.issues.update({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                
            })
            */