name: Publish Release
on: workflow_dispatch
jobs:
  job:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
    - name: Validate the release
      uses: actions/github-script@v4
      with:
        script: |
          console.log('X0')
          const tag = "v" + "${{ github.ref }}".substring(19)
          const rel = await github.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: tag
          })
          if (rel === null) {
            core.setFailed("Could not find a release for tag " + tag)
          }
      
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Finalize the release
      run: |
        version="${{ github.ref }}"
        version="${version:19}" # trim starting 'refs/heads/release/' (19 chars)
        echo "Tag ref ${{ github.ref }} as v$version"
        git tag v$version
        git config user.email "github-actions@zpqrtbnk.net"
        git config user.name "GitHub Actions (Do Something)"
        git push --tags
        git push :${{ github.ref }}

    - name: Publish the release
      uses: actions/github-script@v4
      with:
        script: |
          const tag = "v" + "${{ github.ref }}".substring(19)
          const rel = await github.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: tag
          })
          await github.repos.updateRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: rel.id,
            draft: false
          })