#
# Workflow: Build PR
#

name: Build PR (Organization, Branch)
on: pull_request_target

jobs:

  build-pr:

    name: "Build PR (Organization, Branch) #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.get-refs.ref }}

    steps:
    
      - name: Step
        shell: bash
        run: |
          echo "PR #${{ github.event.pull_request.number }}"
          if [ -z "${{ secrets.SOME_SECRET_TOKEN }}" ]; then
            echo "SECRET IS ABSENT"
          else
            echo "SECRET IS PRESENT"
          fi
          echo "login = ${{ github.event.pull_request.head.repo.owner.login }}"
          echo "login = ${{ github.event.pull_request_target.head.repo.owner.login }}"
          echo "${{ secrets }}"
          
      - name: Get Refs
        id: get-refs
        shell: bash
        run: |
          echo "ref=refs/pull/${{ github.event.pull_request.number }}/merge" >> $GITHUB_OUTPUT
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Report
        shell: bash
        run: |
          git log --graph --pretty=format':%h%d %s %an, %ar' | head -n 12

  build-pr-call:
  
    name: "Call (Organization, Branch)"        
    needs: build-pr
    uses: ./.github/workflows/callme.yml
    secrets: {}
    permissions: {}
    with:
      something: false
      ref: ${{ needs.build-pr.ref }}