#
# Workflow: Build PR
#

name: Build PR (Community, Branch)
on: pull_request

jobs:

  build-pr:

    name: "Build PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
    runs-on: ubuntu-latest

    steps:
    
      - name: Step 1
        shell: bash
        run: echo "step 1 of \#${{ github.event.pull_request.number }}"
        
      - name: Step 2
        shell: bash
        run: echo "step 2 of \#${{ github.event.pull_request.number }}"

      - name: Step 3
        shell: bash
        run: |
          if [ -z "${{ secrets.SOME_SECRET_TOKEN }}" ]; then
            echo "SECRET IS ABSENT"
          else
            echo "SECRET IS PRESENT"
          fi

  build-pr-call:
    name: "Build PR Call"
    uses: ./.github/workflows/callme.yml
    secrets: inherit